apiVersion: v1
kind: ConfigMap
metadata:
  name: acquis-configmap
data:
  acquis.yaml: |-
    {{- $valid := required "You need to specify at least one pod for logs read" .Values.agent.acquisition }}
    {{- $container_runtime := .Values.container_runtime }}
    {{- range .Values.agent.acquisition }}
    filenames:
      - /var/log/containers/{{ .podName }}_{{ .namespace }}_*.log
    labels:
      {{- if .type }}
      type: {{ .type }}
      {{- else }}
      type: {{ $container_runtime }}
      {{- end }}
      program: {{ .program }}
    {{- end }}