apiVersion: v1
kind: ConfigMap
metadata:
  name: acquis-configmap
data:
  acquis.yaml: |-
    {{- range .Values.agent.acquisition }}
    filenames:
      - /var/log/containers/{{ .podName }}_{{ .namespace }}_*.log
    labels:
      type: {{ .type }}
      program: {{ .program }}
    {{- end }}