name: Update docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/crowdsec/values.yaml'
      - 'charts/crowdsec/Chart.yaml'
      - 'charts/crowdsec/templates/**.yaml'
  push:
    branches:
      - main
      - add_lint_test
    paths:
      - 'charts/crowdsec/values.yaml'
      - 'charts/crowdsec/Chart.yaml'
      - 'charts/crowdsec/templates/**.yaml'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run chart-testing (install)
        run: ct install